/// ╔══════════════════════════════════════════════════════════╗
/// ║  SIGILLION PERPS — ARCIUM PRIVATE COMPUTATION MODULE    ║
/// ║  All functions here run INSIDE the Arcium MPC cluster.  ║
/// ║  Inputs are secret-shared; only outputs are revealed.   ║
/// ╚══════════════════════════════════════════════════════════╝

/// Compute PnL without revealing position size on-chain
///
/// Inputs (private, secret-shared across Arcium nodes):
///   - position_size_usd: u64   (e.g. 10,000 USDC)
///   - direction: u8            (0 = LONG, 1 = SHORT)
///   - entry_price: u64         (price at open)
///   - exit_price: u64          (current oracle price)
///   - leverage: u8
///
/// Output (public, returned to Solana):
///   - pnl: i64                 (positive = profit, negative = loss)
///   - proof: [u8; 64]          (Arcium computation proof)
pub fn compute_pnl(
    position_size_usd: u64,
    direction: u8,
    entry_price: u64,
    exit_price: u64,
    leverage: u8,
) -> (i64, [u8; 64]) {
    let price_diff = exit_price as i64 - entry_price as i64;

    let raw_pnl = if direction == 0 {
        // LONG: profit when price goes up
        (position_size_usd as i64 * price_diff) / entry_price as i64
    } else {
        // SHORT: profit when price goes down
        (position_size_usd as i64 * -price_diff) / entry_price as i64
    };

    let leveraged_pnl = raw_pnl * leverage as i64;

    // Proof is generated by Arcium MPC — stub for demo
    let proof = [0u8; 64];

    (leveraged_pnl, proof)
}

/// Check if position should be liquidated
///
/// Returns (should_liquidate: bool, proof: [u8; 64])
/// The bool is the ONLY information revealed — not the margin remaining
pub fn check_liquidation(
    position_size_usd: u64,
    entry_price: u64,
    current_price: u64,
    leverage: u8,
    direction: u8,
) -> (bool, [u8; 64]) {
    let maintenance_margin = 5u64; // 5% maintenance margin
    let margin = position_size_usd / leverage as u64;

    let loss = if direction == 0 {
        if current_price < entry_price {
            (entry_price - current_price) * position_size_usd / entry_price
        } else { 0 }
    } else {
        if current_price > entry_price {
            (current_price - entry_price) * position_size_usd / entry_price
        } else { 0 }
    };

    let should_liquidate = loss * 100 >= margin * (100 - maintenance_margin);
    let proof = [0u8; 64];

    (should_liquidate, proof)
}
